export const customLabels = {
    AF: { primary: "AF", secondary: "+93" },
    AX: { primary: "AX", secondary: "+358" },
    AL: { primary: "AL", secondary: "+355" },
    DZ: { primary: "DZ", secondary: "+213" },
    AS: { primary: "AS", secondary: "+1684" },
    AD: { primary: "AD", secondary: "+376" },
    AO: { primary: "AO", secondary: "+244" },
    AI: { primary: "AI", secondary: "+1264" },
    AQ: { primary: "AQ", secondary: "+672" },
    AG: { primary: "AG", secondary: "+1268" },
    AR: { primary: "AR", secondary: "+54" },
    AM: { primary: "AM", secondary: "+374" },
    AW: { primary: "AW", secondary: "+297" },
    AU: { primary: "AU", secondary: "+61" },
    AT: { primary: "AT", secondary: "+43" },
    AZ: { primary: "AZ", secondary: "+994" },
    BS: { primary: "BS", secondary: "+1242" },
    BH: { primary: "BH", secondary: "+973" },
    BD: { primary: "BD", secondary: "+880" },
    BB: { primary: "BB", secondary: "+1246" },
    BY: { primary: "BY", secondary: "+375" },
    BE: { primary: "BE", secondary: "+32" },
    BZ: { primary: "BZ", secondary: "+501" },
    BJ: { primary: "BJ", secondary: "+229" },
    BM: { primary: "BM", secondary: "+1441" },
    BT: { primary: "BT", secondary: "+975" },
    BO: { primary: "BO", secondary: "+591" },
    BA: { primary: "BA", secondary: "+387" },
    BW: { primary: "BW", secondary: "+267" },
    BR: { primary: "BR", secondary: "+55" },
    IO: { primary: "IO", secondary: "+246" },
    BN: { primary: "BN", secondary: "+673" },
    BG: { primary: "BG", secondary: "+359" },
    BF: { primary: "BF", secondary: "+226" },
    BI: { primary: "BI", secondary: "+257" },
    KH: { primary: "KH", secondary: "+855" },
    CM: { primary: "CM", secondary: "+237" },
    CA: { primary: "CA", secondary: "+1" },
    CV: { primary: "CV", secondary: "+238" },
    KY: { primary: "KY", secondary: "+345" },
    CF: { primary: "CF", secondary: "+236" },
    TD: { primary: "TD", secondary: "+235" },
    CL: { primary: "CL", secondary: "+56" },
    CN: { primary: "CN", secondary: "+86" },
    CX: { primary: "CX", secondary: "+61" },
    CC: { primary: "CC", secondary: "+61" },
    CO: { primary: "CO", secondary: "+57" },
    KM: { primary: "KM", secondary: "+269" },
    CG: { primary: "CG", secondary: "+242" },
    CD: { primary: "CD", secondary: "+243" },
    CK: { primary: "CK", secondary: "+682" },
    CR: { primary: "CR", secondary: "+506" },
    CI: { primary: "CI", secondary: "+225" },
    HR: { primary: "HR", secondary: "+385" },
    CU: { primary: "CU", secondary: "+53" },
    CY: { primary: "CY", secondary: "+357" },
    CZ: { primary: "CZ", secondary: "+420" },
    DK: { primary: "DK", secondary: "+45" },
    DJ: { primary: "DJ", secondary: "+253" },
    DM: { primary: "DM", secondary: "+1767" },
    DO: { primary: "DO", secondary: "+1849" },
    EC: { primary: "EC", secondary: "+593" },
    EG: { primary: "EG", secondary: "+20" },
    SV: { primary: "SV", secondary: "+503" },
    GQ: { primary: "GQ", secondary: "+240" },
    ER: { primary: "ER", secondary: "+291" },
    EE: { primary: "EE", secondary: "+372" },
    ET: { primary: "ET", secondary: "+251" },
    FK: { primary: "FK", secondary: "+500" },
    FO: { primary: "FO", secondary: "+298" },
    FJ: { primary: "FJ", secondary: "+679" },
    FI: { primary: "FI", secondary: "+358" },
    FR: { primary: "FR", secondary: "+33" },
    GF: { primary: "GF", secondary: "+594" },
    PF: { primary: "PF", secondary: "+689" },
    GA: { primary: "GA", secondary: "+241" },
    GM: { primary: "GM", secondary: "+220" },
    GE: { primary: "GE", secondary: "+995" },
    DE: { primary: "DE", secondary: "+49" },
    GH: { primary: "GH", secondary: "+233" },
    GI: { primary: "GI", secondary: "+350" },
    GR: { primary: "GR", secondary: "+30" },
    GL: { primary: "GL", secondary: "+299" },
    GD: { primary: "GD", secondary: "+1473" },
    GP: { primary: "GP", secondary: "+590" },
    GU: { primary: "GU", secondary: "+1671" },
    GT: { primary: "GT", secondary: "+502" },
    GG: { primary: "GG", secondary: "+44" },
    GN: { primary: "GN", secondary: "+224" },
}


export const Nationalities = {
    AF: "Afghan",
    AX: "Åland Islander",
    AL: "Albanian",
    DZ: "Algerian",
    AS: "American Samoan",
    AD: "Andorran",
    AO: "Angolan",
    AI: "Anguillan",
    AQ: "Antarctican",
    AG: "Antiguan and Barbudan",
    AR: "Argentinian",
    AM: "Armenian",
    AW: "Aruban",
    AU: "Australian",
    AT: "Austrian",
    AZ: "Azerbaijani",
    BS: "Bahamian",
    BH: "Bahraini",
    BD: "Bangladeshi",
    BB: "Barbadian",
    BY: "Belarusian",
    BE: "Belgian",
    BZ: "Belizean",
    BJ: "Beninese",
    BM: "Bermudian",
    BT: "Bhutanese",
    BO: "Bolivian",
    BA: "Bosnian and Herzegovinian",
    BW: "Motswana",
    BR: "Brazilian",
    IO: "British Indian Ocean Territory",
    BN: "Bruneian",
    BG: "Bulgarian",
    BF: "Burkinabé",
    BI: "Burundian",
    KH: "Cambodian",
    CM: "Cameroonian",
    CA: "Canadian",
    CV: "Cape Verdean",
    KY: "Caymanian",
    CF: "Central African",
    TD: "Chadian",
    CL: "Chilean",
    CN: "Chinese",
    CX: "Christmas Islander",
    CC: "Cocos Islander",
    CO: "Colombian",
    KM: "Comoran",
    CG: "Congolese",
    CD: "Congolese",
    CK: "Cook Islander",
    CR: "Costa Rican",
    CI: "Ivorian",
    HR: "Croatian",
    CU: "Cuban",
    CY: "Cypriot",
    CZ: "Czech",
    DK: "Danish",
    DJ: "Djiboutian",
    DM: "Dominican",
    DO: "Dominican",
    EC: "Ecuadorian",
    EG: "Egyptian",
    SV: "Salvadoran",
    GQ: "Equatorial Guinean",
    ER: "Eritrean",
    EE: "Estonian",
    ET: "Ethiopian",
    FK: "Falkland Islander",
    FO: "Faroese",
    FJ: "Fijian",
    FI: "Finnish",
    FR: "French",
    GF: "French Guianese",
    PF: "French Polynesian",
    GA: "Gabonese",
    GM: "Gambian",
    GE: "Georgian",
    DE: "German",
    GH: "Ghanaian",
    GI: "Gibraltar",
    GR: "Greek",
    GL: "Greenlandic",
    GD: "Grenadian",
    GP: "Guadeloupian",
    GU: "Guamanian",
    GT: "Guatemalan",
    GG: "Channel Islander",
    GN: "Guinean",
    GW: "Bissau-Guinean",
    GY: "Guyanese",
    HT: "Haitian",
    VA: "Vatican",
    HN: "Honduran",
    HK: "Hong Kong",
    HU: "Hungarian",
    IS: "Icelander",
    IN: "Indian",
    ID: "Indonesian",
    IR: "Iranian",
    IQ: "Iraqi",
    IE: "Irish",
    IM: "Manx",
    IL: "Israeli",
    IT: "Italian",
    JM: "Jamaican",
    JP: "Japanese",
    JE: "Jersey",
    JO: "Jordanian",
    KZ: "Kazakhstani",
    KE: "Kenyan",
    KI: "I-Kiribati",
    KP: "North Korean",
    KR: "South Korean",
    KW: "Kuwaiti",
    KG: "Kyrgyzstani",
    LA: "Laotian",
    LV: "Latvian",
    LB: "Lebanese",
    LS: "Mosotho",
    LR: "Liberian",
    LY: "Libyan",
    LI: "Liechtensteiner",
    LT: "Lithuanian",
    LU: "Luxembourger",
    MO: "Macanese",
    MK: "Macedonian",
    MG: "Malagasy",
    MW: "Malawian",
    MY: "Malaysian",
    MV: "Maldivian",
    ML: "Malian",
    MT: "Maltese",
    MH: "Marshallese",
    MQ: "Martinican",
    MR: "Mauritanian",
    MU: "Mauritian",
    YT: "Mahoran",
    MX: "Mexican",
    FM: "Micronesian",
    MD: "Moldovan",
    MC: "Monacan",
    MN: "Mongolian",
    ME: "Montenegrin",
    MS: "Montserratian",
    MA: "Moroccan",
    MZ: "Mozambican",
    MM: "Burmese",
    NA: "Namibian",
    NR: "Nauruan",
    NP: "Nepalese",
    NL: "Dutch",
    AN: "Dutch",
    NC: "New Caledonian",
    NZ: "New Zealander",
    NI: "Nicaraguan",
    NE: "Nigerien",
    NG: "Nigerian",
    NU: "Niuean",
    NF: "Norfolk Islander",
    MP: "Northern Marianan",
    NO: "Norwegian",
    OM: "Omani",
    PK: "Pakistani",
    PW: "Palauan",
    PS: "Palestinian",
    PA: "Panamanian",
    PG: "Papua New Guinean",
    PY: "Paraguayan",
    PE: "Peruvian",
    PH: "Filipino",
    PN: "Pitcairn Islander",
    PL: "Polish",
    PT: "Portuguese",
    PR: "Puerto Rican",
    QA: "Qatari",
    RO: "Romanian",
    RU: "Russian",
    RW: "Rwandan",
    RE: "Réunionese",
    BL: "Saint Barthélemy Islander",
    SH: "Saint Helenian",
    KN: "Kittian and Nevisian",
    LC: "Saint Lucian",
    MF: "Saint Martinoise",
    PM: "Saint-Pierrais et Miquelonnais",
    VC: "Saint Vincentian",
    WS: "Samoan",
    SM: "Sammarinese",
    ST: "São Toméan",
    SA: "Saudi Arabian",
    SN: "Senegalese",
    RS: "Serbian",
    SC: "Seychellois",
    SL: "Sierra Leonean",
    SG: "Singaporean",
    SK: "Slovak",
    SI: "Slovene",
    SB: "Solomon Islander",
    SO: "Somali",
    ZA: "South African",
    SS: "South Sudanese",
    GS: "South Georgia and the South Sandwich Islander",
    ES: "Spanish",
    LK: "Sri Lankan",
    SD: "Sudanese",
    SR: "Surinamer",
    SJ: "Svalbardian and Jan Mayener",
    SZ: "Swazi",
    SE: "Swedish",
    CH: "Swiss",
    SY: "Syrian",
    TW: "Taiwanese",
    TJ: "Tajikistani",
    TZ: "Tanzanian",
    TH: "Thai",
    TL: "Timorese",
    TG: "Togolese",
    TK: "Tokelauan",
    TO: "Tongan",
    TT: "Trinidadian",
    TN: "Tunisian",
    TR: "Turkish",
    TM: "Turkmen",
    TC: "Turks and Caicos Islander",
    TV: "Tuvaluan",
    UG: "Ugandan",
    UA: "Ukrainian",
    AE: "Emirati",
    GB: "British",
    US: "American",
    UY: "Uruguayan",
    UZ: "Uzbekistani",
    VU: "Ni-Vanuatu",
    VE: "Venezuelan",
    VN: "Vietnamese",
    VG: "British Virgin Islander",
    VI: "U.S. Virgin Islander",
    WF: "Wallisian and Futunan",
    YE: "Yemeni",
    ZM: "Zambian",
    ZW: "Zimbabwean"
};

export const placeOfBirthObject = {
    AF: "Afghanistan",
    AX: "Aland Islands",
    AL: "Albania",
    DZ: "Algeria",
    AS: "American Samoa",
    AD: "Andorra",
    AO: "Angola",
    AI: "Anguilla",
    AQ: "Antarctica",
    AG: "Antigua and Barbuda",
    AR: "Argentina",
    AM: "Armenia",
    AW: "Aruba",
    AU: "Australia",
    AT: "Austria",
    AZ: "Azerbaijan",
    BS: "Bahamas",
    BH: "Bahrain",
    BD: "Bangladesh",
    BB: "Barbados",
    BY: "Belarus",
    BE: "Belgium",
    BZ: "Belize",
    BJ: "Benin",
    BM: "Bermuda",
    BT: "Bhutan",
    BO: "Bolivia, Plurinational State of",
    BA: "Bosnia and Herzegovina",
    BW: "Botswana",
    BR: "Brazil",
    IO: "British Indian Ocean Territory",
    BN: "Brunei Darussalam",
    BG: "Bulgaria",
    BF: "Burkina Faso",
    BI: "Burundi",
    KH: "Cambodia",
    CM: "Cameroon",
    CA: "Canada",
    CV: "Cape Verde",
    KY: "Cayman Islands",
    CF: "Central African Republic",
    TD: "Chad",
    CL: "Chile",
    CN: "China",
    CX: "Christmas Island",
    CC: "Cocos (Keeling) Islands",
    CO: "Colombia",
    KM: "Comoros",
    CG: "Congo",
    CD: "Congo, The Democratic Republic of the Congo",
    CK: "Cook Islands",
    CR: "Costa Rica",
    CI: "Cote d'Ivoire",
    HR: "Croatia",
    CU: "Cuba",
    CY: "Cyprus",
    CZ: "Czech Republic",
    DK: "Denmark",
    DJ: "Djibouti",
    DM: "Dominica",
    DO: "Dominican Republic",
    EC: "Ecuador",
    EG: "Egypt",
    SV: "El Salvador",
    GQ: "Equatorial Guinea",
    ER: "Eritrea",
    EE: "Estonia",
    ET: "Ethiopia",
    FK: "Falkland Islands (Malvinas)",
    FO: "Faroe Islands",
    FJ: "Fiji",
    FI: "Finland",
    FR: "France",
    GF: "French Guiana",
    PF: "French Polynesia",
    GA: "Gabon",
    GM: "Gambia",
    GE: "Georgia",
    DE: "Germany",
    GH: "Ghana",
    GI: "Gibraltar",
    GR: "Greece",
    GL: "Greenland",
    GD: "Grenada",
    GP: "Guadeloupe",
    GU: "Guam",
    GT: "Guatemala",
    GG: "Guernsey",
    GN: "Guinea",
    GW: "Guinea-Bissau",
    GY: "Guyana",
    HT: "Haiti",
    VA: "Holy See (Vatican City State)",
    HN: "Honduras",
    HK: "Hong Kong",
    HU: "Hungary",
    IS: "Iceland",
    IN: "India",
    ID: "Indonesia",
    IR: "Iran, Islamic Republic of Persian Gulf",
    IQ: "Iraq",
    IE: "Ireland",
    IM: "Isle of Man",
    IL: "Israel",
    IT: "Italy",
    JM: "Jamaica",
    JP: "Japan",
    JE: "Jersey",
    JO: "Jordan",
    KZ: "Kazakhstan",
    KE: "Kenya",
    KI: "Kiribati",
    KP: "Korea, Democratic People's Republic of Korea",
    KR: "Korea, Republic of South Korea",
    KW: "Kuwait",
    KG: "Kyrgyzstan",
    LA: "Laos",
    LV: "Latvia",
    LB: "Lebanon",
    LS: "Lesotho",
    LR: "Liberia",
    LY: "Libyan Arab Jamahiriya",
    LI: "Liechtenstein",
    LT: "Lithuania",
    LU: "Luxembourg",
    MO: "Macao",
    MK: "Macedonia",
    MG: "Madagascar",
    MW: "Malawi",
    MY: "Malaysia",
    MV: "Maldives",
    ML: "Mali",
    MT: "Malta",
    MH: "Marshall Islands",
    MQ: "Martinique",
    MR: "Mauritania",
    MU: "Mauritius",
    YT: "Mayotte",
    MX: "Mexico",
    FM: "Micronesia, Federated States of Micronesia",
    MD: "Moldova",
    MC: "Monaco",
    MN: "Mongolia",
    ME: "Montenegro",
    MS: "Montserrat",
    MA: "Morocco",
    MZ: "Mozambique",
    MM: "Myanmar",
    NA: "Namibia",
    NR: "Nauru",
    NP: "Nepal",
    NL: "Netherlands",
    AN: "Netherlands Antilles",
    NC: "New Caledonia",
    NZ: "New Zealand",
    NI: "Nicaragua",
    NE: "Niger",
    NG: "Nigeria",
    NU: "Niue",
    NF: "Norfolk Island",
    MP: "Northern Mariana Islands",
    NO: "Norway",
    OM: "Oman",
    PK: "Pakistan",
    PW: "Palau",
    PS: "Palestinian Territory, Occupied",
    PA: "Panama",
    PG: "Papua New Guinea",
    PY: "Paraguay",
    PE: "Peru",
    PH: "Philippines",
    PN: "Pitcairn",
    PL: "Poland",
    PT: "Portugal",
    PR: "Puerto Rico",
    QA: "Qatar",
    RO: "Romania",
    RU: "Russia",
    RW: "Rwanda",
    RE: "Reunion",
    BL: "Saint Barthelemy",
    SH: "Saint Helena, Ascension and Tristan Da Cunha",
    KN: "Saint Kitts and Nevis",
    LC: "Saint Lucia",
    MF: "Saint Martin",
    PM: "Saint Pierre and Miquelon",
    VC: "Saint Vincent and the Grenadines",
    WS: "Samoa",
    SM: "San Marino",
    ST: "Sao Tome and Principe",
    SA: "Saudi Arabia",
    SN: "Senegal",
    RS: "Serbia",
    SC: "Seychelles",
    SL: "Sierra Leone",
    SG: "Singapore",
    SK: "Slovakia",
    SI: "Slovenia",
    SB: "Solomon Islands",
    SO: "Somalia",
    ZA: "South Africa",
    SS: "South Sudan",
    GS: "South Georgia and the South Sandwich Islands",
    ES: "Spain",
    LK: "Sri Lanka",
    SD: "Sudan",
    SR: "Suriname",
    SJ: "Svalbard and Jan Mayen",
    SZ: "Swaziland",
    SE: "Sweden",
    CH: "Switzerland",
    SY: "Syrian Arab Republic",
    TW: "Taiwan",
    TJ: "Tajikistan",
    TZ: "Tanzania, United Republic of Tanzania",
    TH: "Thailand",
    TL: "Timor-Leste",
    TG: "Togo",
    TK: "Tokelau",
    TO: "Tonga",
    TT: "Trinidad and Tobago",
    TN: "Tunisia",
    TR: "Turkey",
    TM: "Turkmenistan",
    TC: "Turks and Caicos Islands",
    TV: "Tuvalu",
    UG: "Uganda",
    UA: "Ukraine",
    AE: "United Arab Emirates",
    GB: "United Kingdom",
    US: "United States",
    UY: "Uruguay",
    UZ: "Uzbekistan",
    VU: "Vanuatu",
    VE: "Venezuela, Bolivarian Republic of Venezuela",
    VN: "Vietnam",
    VG: "Virgin Islands, British",
    VI: "Virgin Islands, U.S.",
    WF: "Wallis and Futuna",
    YE: "Yemen",
    ZM: "Zambia",
    ZW: "Zimbabwe"
};
