export const sessions = [
  {
    id: 1,
    ar_name: "الأشعه المقطعيه علي الدماغ",
    en_name: "Brain CT Scan",
    image: "/images/TherapySessions1/session2.svg",
    type: "individual",
  },
  {
    id: 2,
    ar_name: "التلعثم",
    en_name: "Stuttering",
    image: "/images/TherapySessions1/session1.svg",
    type: "individual",
  },
  {
    id: 3,
    ar_name: "اورام ليفيه",
    en_name: "Fibroids",
    image: "/images/TherapySessions1/1.svg",
    type: "group",
  },
  {
    id: 4,
    ar_name: "السكري النوع الأول",
    en_name: "Type 1 Diabetes",
    image: "/images/TherapySessions1/2.svg",
    type: "group",
  },
  {
    id: 5,
    ar_name: "السكري النوع الثاني",
    en_name: "Type 2 Diabetes",
    image: "/images/TherapySessions1/3.svg",
    type: "group",
  },
  {
    id: 6,
    ar_name: "الغده الدرقيه",
    en_name: "Thyroid Gland",
    image: "/images/TherapySessions1/4.svg",
    type: "group",
  },
  {
    id: 7,
    ar_name: "الآم أسفل الظهر",
    en_name: "Back Pain",
    image: "/images/TherapySessions1/5.svg",
    type: "group",
  },
  {
    id: 8,
    ar_name: "تكيس المبايض",
    en_name: "Ovarian Cyst",
    image: "/images/TherapySessions1/6.svg",
    type: "group",
  },
  {
    id: 9,
    ar_name: "أورام الثدي",
    en_name: "Breast Cancer",
    image: "/images/TherapySessions1/7.svg",
    type: "group",
  },
  {
    id: 10,
    ar_name: "التصلب اللويحي",
    en_name: "Multiple Sclerosis",
    image: "/images/TherapySessions1/8.svg",
    type: "group",
  },
  {
    id: 11,
    ar_name: "الصدفية والإكزيما",
    en_name: "Psoriasis and Eczema",
    image: "/images/TherapySessions1/9.svg",
    type: "group",
  },
];
