import { ThemeProvider } from "@mui/material";
import { Toaster } from "sonner";
import { theme } from "@/utils/Theme/theme";
import "../globals.css";
import FinalLayout from "./FinalLayout";

export const metadata = {
  title: "Healing Dashboard",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <FinalLayout>{children}</FinalLayout>;
}
