import DashboardNavbar from "../components/Dashboard/Navbar/page";
import "../globals.css";
import "../styles/sass/Dashboard/main.scss";
export const metadata = {
  title: "Healing Dashboard",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" href="/images/healing-logo.svg" sizes="any" />
      <body style={{ padding: "0", margin: "0", background: "#F8F8F8" }}>
        <DashboardNavbar />
        {children}
      </body>
    </html>
  );
}
